const URL='https://dfjffbzbmkitmnsiifib.supabase.co', KEY='sb_publishable_ntEqcHgqsbxQbg_18j_ztg_IdYZcyfu', db=supabase.createClient(URL,KEY), app=document.querySelector('#app'), bucket='team-logos';
let teams=[], user=null, history=[], oldPos=new Map(), oldRanks=new Map(), uploadId=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const order=()=>[...teams].sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name));
const logo=t=>t.logo?`<img class="logo" src="${esc(t.logo)}" alt="">`:`<span class="logo placeholder">${esc(t.name[0]||'?')}</span>`;
function capture(){oldPos=new Map([...document.querySelectorAll('[data-id]')].map(e=>[e.dataset.id,e.getBoundingClientRect()]));}
function motion(){let ranks=new Map;document.querySelectorAll('[data-id]').forEach(e=>{let p=oldPos.get(e.dataset.id),n=e.getBoundingClientRect(),r=+e.dataset.rank;ranks.set(e.dataset.id,r);if(p&&Math.abs(p.top-n.top)>1){e.style.transition='none';e.style.transform=`translateY(${p.top-n.top}px)`;requestAnimationFrame(()=>requestAnimationFrame(()=>{e.style.transition='transform .62s cubic-bezier(.22,1,.36,1)';e.style.transform=''}));}if(oldRanks.has(e.dataset.id)&&oldRanks.get(e.dataset.id)!==r){e.classList.add('changed');setTimeout(()=>e.classList.remove('changed'),850)}});oldRanks=ranks}
async function read(){let s=await db.auth.getSession();user=s.data.session?.user||null;let q=await db.from('teams').select('*');if(!q.error){teams=q.data||[];render()}}
async function save(){if(!user)return alert('กรุณาล็อกอินแอดมิน');let q=await db.from('teams').upsert(teams);if(q.error)alert(q.error.message);render()}
async function login(){let email=prompt('อีเมลแอดมิน Supabase'),password=prompt('รหัสผ่าน');if(!email||!password)return;let q=await db.auth.signInWithPassword({email,password});if(q.error)alert(q.error.message);else read()}
async function upload(file,id){if(!file)return;if(!['image/png','image/jpeg'].includes(file.type))return alert('รองรับ PNG / JPG / JPEG เท่านั้น');if(file.size>2097152)return alert('ไฟล์ใหญ่เกิน 2 MB');let ext=file.type==='image/png'?'png':'jpg',path=`${user.id}/${id}-${Date.now()}.${ext}`,q=await db.storage.from(bucket).upload(path,file,{contentType:file.type});if(q.error)return alert(q.error.message);let t=teams.find(x=>x.id===id);t.logo=db.storage.from(bucket).getPublicUrl(path).data.publicUrl;save()}
const nav=a=>`<nav><a class="${a==='admin'?'on':''}" href="/admin">ควบคุม</a><a class="${a==='live'?'on':''}" href="/live">คะแนนสด</a><a href="/overlay" target="_blank">OBS Overlay ↗</a></nav>`;
function row(t,i,admin=false){return `<article class="row" data-id="${t.id}" data-rank="${i+1}"><b class="rank">${String(i+1).padStart(2,'0')}</b><div class="team">${logo(t)}<strong>${esc(t.name)}</strong></div><b class="points">${t.score}</b>${admin?`<div class="actions"><button data-up="${t.id}">↑</button><button data-score="-1" data-id="${t.id}">−</button><button class="plus" data-score="1" data-id="${t.id}">+</button><button class="del" data-del="${t.id}">×</button></div>`:''}</article>`}
function admin(){let rows=order().map((t,i)=>row(t,i,true)).join('');app.innerHTML=`<main class="shell"><header><div><small>PUBG TOURNAMENT CONTROL</small><h1>Live Scoreboard</h1><p>จัดอันดับแบบเรียลไทม์สำหรับสตรีม</p></div><div>${user?`<button id="logout">ออกจากระบบ</button>`:`<button id="login" class="primary">ล็อกอินแอดมิน</button>`}${nav('admin')}</div></header><div class="status"><i></i>${teams.length}/25 ทีม · ${user?'เชื่อมต่อ Supabase แล้ว':'ล็อกอินก่อนแก้ไขคะแนน'}</div><section class="add"><h2>เพิ่มทีม</h2><form id="add"><input name="name" required placeholder="ชื่อทีม"><input name="score" type="number" value="0" min="0" placeholder="คะแนน"><button class="primary">+ เพิ่มทีม</button></form><em>กด ↑ ข้างทีมเพื่ออัปโหลดโลโก้ PNG/JPG ไม่เกิน 2 MB</em></section><div class="head"><span>RANK</span><span>TEAM</span><span>PTS</span><span>CONTROL</span></div><section class="list">${rows||'<p class="empty">ยังไม่มีทีม</p>'}</section><input id="file" hidden type="file" accept="image/png,image/jpeg"><footer><button id="undo">↶ ย้อนกลับ</button><button id="reset" class="danger">รีเซ็ตคะแนน</button></footer></main>`;bind()}
function bind(){document.querySelector('#login')?.addEventListener('click',login);document.querySelector('#logout')?.addEventListener('click',async()=>{await db.auth.signOut();read()});document.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{if(!user)return login();history.push(JSON.stringify(teams));let t=teams.find(x=>x.id===b.dataset.id);t.score=Math.max(0,t.score+(+b.dataset.score));save()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(user&&confirm('ลบทีมนี้?')){teams=teams.filter(t=>t.id!==b.dataset.del);db.from('teams').delete().eq('id',b.dataset.del);save()}});document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{if(!user)return login();uploadId=b.dataset.up;document.querySelector('#file').click()});document.querySelector('#file').onchange=e=>upload(e.target.files[0],uploadId);document.querySelector('#add').onsubmit=e=>{e.preventDefault();if(!user)return login();if(teams.length>=25)return alert('สูงสุด 25 ทีม');let f=new FormData(e.target);teams.push({id:crypto.randomUUID(),name:f.get('name'),score:+f.get('score')||0,logo:''});e.target.reset();save()};document.querySelector('#reset').onclick=()=>{if(user&&confirm('รีเซ็ตคะแนน?')){teams.forEach(t=>t.score=0);save()}};document.querySelector('#undo').onclick=()=>{let h=history.pop();if(h){teams=JSON.parse(h);save()}}}
function live(){app.innerHTML=`<main class="shell"><header><div><small>LIVE UPDATE</small><h1>คะแนนสด</h1></div>${nav('live')}</header><section class="list live">${order().map((t,i)=>row(t,i)).join('')}</section></main>`}
function overlay(){document.body.className='overlay';app.innerHTML=`<section class="board"><header><div><small>OFFICIAL LEADERBOARD</small><h2>PUBG ตารางคะแนน</h2></div><b>● LIVE</b></header><div class="labels">RANK <span>TEAM</span> PTS</div>${order().slice(0,10).map((t,i)=>`<article class="o-row" data-id="${t.id}" data-rank="${i+1}"><b>${String(i+1).padStart(2,'0')}</b>${logo(t)}<strong>${esc(t.name)}</strong><b>${t.score}</b></article>`).join('')}</section>`}
function render(){capture();let v=location.pathname.split('/').filter(Boolean).pop()||'admin';({admin,live,overlay}[v]||admin)();motion()}
db.channel('score-live').on('postgres_changes',{event:'*',schema:'public',table:'teams'},read).subscribe();read();render();
