const SUPABASE_URL='https://dfjffbzbmkitmnsiifib.supabase.co',KEY='sb_publishable_ntEqcHgqsbxQbg_18j_ztg_IdYZcyfu',db=window.supabase?.createClient(SUPABASE_URL,KEY),app=document.querySelector('#app'),bucket='team-logos',OVERLAY_TEAM_LIMIT=16;
let teams=[],tournament=null,maps=[],scores=[],draft={},user=null,oldPos=new Map(),oldRanks=new Map(),uploadId=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rank=a=>[...a].sort((x,y)=>y.points-x.points||y.kills-x.kills||x.name.localeCompare(y.name));
const logo=t=>t.logo?`<img class="logo" src="${esc(t.logo)}" alt="">`:`<span class="logo placeholder">${esc((t.name||'?')[0])}</span>`;
const current=()=>maps.find(m=>m.map_number===tournament?.current_map);
const dFor=id=>draft[id]||{kills:0,placement_points:0};
function totals(){let visible=new Set(maps.filter(m=>m.status==='live'||m.status==='completed').map(m=>m.id)),out=teams.map(t=>({id:t.id,name:t.name,logo:t.logo,points:0,kills:0}));scores.filter(s=>visible.has(s.map_id)).forEach(s=>{let t=out.find(x=>x.id===s.team_id);if(t){t.points+=(s.kills||0)+(s.placement_points||0);t.kills+=s.kills||0}});return rank(out)}
function capture(){oldPos=new Map([...document.querySelectorAll('[data-id]')].map(e=>[e.dataset.id,e.getBoundingClientRect()]));}
function motion(){}
function setSave(text,state='saved'){document.querySelectorAll('[data-save-state]').forEach(e=>{e.textContent=text;e.dataset.state=state})}
async function read(){if(!db)return renderError('Supabase failed to load.');let s=await db.auth.getSession(),tq=await db.from('tournaments').select('*').eq('status','active').limit(1).maybeSingle(),teamq=await db.from('teams').select('*');user=s.data.session?.user||null;if(tq.error||teamq.error)return renderError(tq.error?.message||teamq.error?.message);tournament=tq.data;teams=teamq.data||[];maps=[];scores=[];draft={};if(tournament){let mq=await db.from('maps').select('*').eq('tournament_id',tournament.id).order('map_number'),ids=(mq.data||[]).map(m=>m.id),sq=ids.length?await db.from('map_scores').select('*').in('map_id',ids):{data:[]};if(mq.error||sq.error)return renderError(mq.error?.message||sq.error?.message);maps=mq.data||[];scores=sq.data||[];let cm=current();if(cm)scores.filter(x=>x.map_id===cm.id).forEach(x=>draft[x.team_id]={kills:x.kills||0,placement_points:x.placement_points||0});}render();}
async function login(){let email=prompt('อีเมลแอดมิน Supabase'),password=prompt('รหัสผ่าน');if(!email||!password)return;let q=await db.auth.signInWithPassword({email,password});if(q.error)alert(q.error.message);else read();}
const nav=a=>`<nav class="nav"><a class="${a==='admin'?'is-active':''}" href="/admin">ADMIN</a><a class="${a==='live'?'is-active':''}" href="/live">LIVE</a><a href="/overlay" target="_blank">OBS OVERLAY ↗</a></nav>`;
function setup(){app.innerHTML=`<main class="shell setup"><header class="topbar"><div><small>TOXIC GREEN · TOURNAMENT CONTROL</small><h1>New Tournament</h1><p>ตั้งค่าจำนวนแมพก่อนเริ่มบันทึกผล</p></div>${nav('admin')}</header><section class="setup-panel"><small>TOURNAMENT SETUP</small><h2>CREATE MATCH</h2><form id="setup"><input name="name" required maxlength="64" placeholder="TOURNAMENT NAME"><input name="maps" type="number" min="1" max="20" value="3"><button class="primary">START TOURNAMENT</button></form><p>คะแนนต่อแมพ = Kills + Placement Points · ตารางคะแนนรวมจะแสดงผลเฉพาะแมพที่บันทึกแล้ว</p></section></main>`;document.querySelector('#setup').onsubmit=startTournament;}
async function startTournament(e){e.preventDefault();if(!user)return login();let f=new FormData(e.target),total=Math.max(1,Math.min(20,+f.get('maps')||3)),q=await db.from('tournaments').insert({name:f.get('name').trim(),total_maps:total,current_map:1,status:'active'}).select().single();if(q.error)return alert(q.error.message);q=await db.from('maps').insert({tournament_id:q.data.id,map_number:1,status:'live'});if(q.error)return alert(q.error.message);read();}
function metric(label,value,id,field){return `<div class="metric"><button data-adjust="-1" data-field="${field}" data-id="${id}" aria-label="ลด ${label}">−</button><input aria-label="${label}" data-value="${field}" data-id="${id}" type="number" min="0" value="${value}"><button data-adjust="1" data-field="${field}" data-id="${id}" aria-label="เพิ่ม ${label}">+</button></div>`}
function entry(t,i){let d=dFor(t.id),sum=d.kills+d.placement_points,all=totals().find(x=>x.id===t.id);return `<article class="entry-row" data-id="${t.id}" data-rank="${i+1}"><b class="rank">${String(i+1).padStart(2,'0')}</b><div class="team">${logo(t)}<strong>${esc(t.name)}</strong></div>${metric('KILLS',d.kills,t.id,'kills')}${metric('PLACEMENT POINTS',d.placement_points,t.id,'placement_points')}<b class="map-total">${sum}</b><b class="overall-total">${all?.points||0}</b></article>`}
function standings(rows){return `<div class="standings"><div class="score-head"><span>#</span><span>TEAM</span><span>PTS</span><span>KILLS</span></div>${rows.map((t,i)=>`<article class="score-row podium-${i+1}" data-id="${t.id}" data-rank="${i+1}"><b class="rank">${String(i+1).padStart(2,'0')}</b><div class="team">${logo(t)}<strong>${esc(t.name)}</strong></div><b class="display-score">${t.points}</b><b class="display-kills">${t.kills}</b></article>`).join('')||'<p class="empty">NO CONFIRMED MAPS YET</p>'}</div>`}
function admin(){if(!tournament)return setup();let finished=tournament.status==='complete',rows=rank(teams.map(t=>({name:t.name,...t,points:dFor(t.id).kills+dFor(t.id).placement_points,kills:dFor(t.id).kills}))).map(entry).join('');app.innerHTML=`<main class="shell"><header class="topbar"><div><small>TOXIC GREEN · ${esc(tournament.name)}</small><h1>Map ${tournament.current_map} <em>/ ${tournament.total_maps}</em></h1><p>${finished?'TOURNAMENT COMPLETE · ผลการแข่งขันถูกบันทึกแล้ว':'ทุกคะแนน sync ไปยัง Live และ OBS ทันที'}</p></div><div class="top-actions">${user?'<button id="logout">LOG OUT</button>':'<button id="login" class="primary">ADMIN LOGIN</button>'}${nav('admin')}</div></header><section class="command-strip"><div><span class="live-dot"></span><b>${finished?'FINAL RESULTS':'LIVE · MAP '+tournament.current_map}</b><span>${teams.length} TEAMS</span></div><span data-save-state data-state="saved">${finished?'COMPLETE':'LIVE SYNCED'}</span></section>${finished?'':`<section class="map-entry"><div class="entry-title"><small>LIVE MAP ENTRY</small><h2>MAP ${tournament.current_map} RESULTS</h2></div><div class="entry-head"><span>RANK</span><span>TEAM</span><span>KILLS</span><span>PLACE PTS</span><span>MAP PTS</span><span>TOTAL PTS</span></div><div class="entry-list">${rows||'<p class="empty">ADD TEAMS BEFORE RECORDING RESULTS</p>'}</div><div class="map-actions"><button id="discard">RESET LIVE MAP</button><button id="save-map" class="primary" ${teams.length?'':'disabled'}>${tournament.current_map===tournament.total_maps?'END FINAL MAP':'END MAP '+tournament.current_map+' & START MAP '+(tournament.current_map+1)}</button></div></section>`}<section class="totals"><div><small>LIVE TOURNAMENT TOTAL</small><h2>TOURNAMENT STANDINGS</h2></div>${standings(totals())}</section><section class="team-admin"><h2>Teams</h2><form id="add-team"><input name="name" required maxlength="32" placeholder="TEAM NAME"><button class="primary">+ ADD TEAM</button></form><div class="team-pills">${teams.map(t=>`<div>${logo(t)}<b>${esc(t.name)}</b><button data-del="${t.id}">×</button></div>`).join('')}</div></section></main>`;bind();}
function bind(){document.querySelector('#login')?.addEventListener('click',login);document.querySelector('#logout')?.addEventListener('click',async()=>{await db.auth.signOut();read()});document.querySelectorAll('[data-adjust]').forEach(b=>b.onclick=()=>{if(!user)return login();let d=dFor(b.dataset.id),f=b.dataset.field;d[f]=Math.max(0,(+d[f]||0)+ +b.dataset.adjust);draft[b.dataset.id]=d;setSave('SYNCING…','saving');syncScore(b.dataset.id);render()});document.querySelectorAll('[data-value]').forEach(i=>i.onchange=()=>{if(!user)return login();let d=dFor(i.dataset.id);d[i.dataset.value]=Math.max(0,parseInt(i.value,10)||0);draft[i.dataset.id]=d;setSave('SYNCING…','saving');syncScore(i.dataset.id);render()});document.querySelector('#discard')?.addEventListener('click',()=>{if(confirm('รีเซ็ตคะแนน Live ของแมพนี้ทั้งหมด?')){teams.forEach(t=>draft[t.id]={kills:0,placement_points:0});teams.forEach(t=>syncScore(t.id));render()}});document.querySelector('#save-map')?.addEventListener('click',saveMap);document.querySelector('#add-team')?.addEventListener('submit',addTeam);document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteTeam(b.dataset.del));}
async function addTeam(e){e.preventDefault();if(!user)return login();let f=new FormData(e.target),q=await db.from('teams').insert({name:f.get('name').trim(),logo:'',score:0,kills:0});if(q.error)return alert(q.error.message);e.target.reset();read();}
async function deleteTeam(id){if(!user||!confirm('ลบทีมนี้?'))return;let q=await db.from('teams').delete().eq('id',id);if(q.error)return alert(q.error.message);read();}
async function syncScore(teamId){let cm=current();if(!cm||!user)return;let d=dFor(teamId),q=await db.from('map_scores').upsert({map_id:cm.id,team_id:teamId,kills:d.kills,placement_points:d.placement_points},{onConflict:'map_id,team_id'});if(q.error){setSave('SYNC FAILED','saving');alert(q.error.message)}else setSave('LIVE SYNCED');}
async function saveMap(){if(!user)return login();let cm=current();if(!cm)return;setSave('ENDING MAP…','saving');let payload=teams.map(t=>({map_id:cm.id,team_id:t.id,kills:dFor(t.id).kills,placement_points:dFor(t.id).placement_points})),q=await db.from('map_scores').upsert(payload,{onConflict:'map_id,team_id'});if(q.error)return alert(q.error.message);let final=tournament.current_map===tournament.total_maps;q=await db.from('maps').update({status:'completed'}).eq('id',cm.id);if(!q.error&&final)q=await db.from('tournaments').update({status:'complete'}).eq('id',tournament.id);if(!q.error&&!final){q=await db.from('maps').insert({tournament_id:tournament.id,map_number:tournament.current_map+1,status:'live'});if(!q.error)q=await db.from('tournaments').update({current_map:tournament.current_map+1}).eq('id',tournament.id)}if(q.error)return alert(q.error.message);draft={};read();}
function live(){if(!tournament)return setup();app.innerHTML=`<main class="shell live-shell"><header class="topbar"><div><small>TOXIC GREEN · ${esc(tournament.name)}</small><h1>Standings</h1><p>${tournament.status==='complete'?'FINAL RESULTS':'LIVE · MAP '+tournament.current_map+' / '+tournament.total_maps}</p></div>${nav('live')}</header>${standings(totals())}</main>`}
function overlay(){if(!tournament)return;app.innerHTML=`<section class="board match-board"><div class="overlay-title">${esc(tournament.name)} <span>${tournament.status==='complete'?'FINAL':'MAP '+tournament.current_map+'/'+tournament.total_maps}</span></div>${standings(totals().slice(0,OVERLAY_TEAM_LIMIT))}</section>`}
function renderError(m){app.innerHTML=`<main class="shell"><section class="empty"><h2>CONNECTION ERROR</h2><p>${esc(m)}</p><button onclick="location.reload()">RETRY</button></section></main>`}
function render(){capture();let v=new URLSearchParams(location.search).get('view')||location.pathname.split('/').filter(Boolean).pop()||'admin';({admin,live,overlay}[v]||admin)();motion();}
if(db){db.channel('score-live').on('postgres_changes',{event:'*',schema:'public',table:'teams'},read).on('postgres_changes',{event:'*',schema:'public',table:'tournaments'},read).on('postgres_changes',{event:'*',schema:'public',table:'maps'},read).on('postgres_changes',{event:'*',schema:'public',table:'map_scores'},read).subscribe();read();render()}else renderError('Supabase failed to load.');
